### PR TITLE
hard coded path

### PR DESCRIPTION
**Pull request by powersln**
Change hard coded path to attribute.

### CODE REVIEW

**Comment by aririikonen** [comment]
Good catch powersln. Thank you! Obviously we need to change this to an attribute, but personally I would put the diag folders under ORACLE_BASE (Oracle default) instead of ORACLE_HOME, so node[:oracle][:ora_base].

Ref. http://docs.oracle.com/database/121/REFRN/refrn10280.htm#REFRN10280

What do you think?

**Comment by powersln** [comment]
Oops that what I mean't.  You are correct.

**Comment by powersln** [comment]
This is my first pull request, I'm a newb.   Do I need to create a new pull request with the updated change or do you handle it?

**Comment by aririikonen** [comment]
Probably just easier to create a new pull request, if you don't mind. I could change it directly to the template, but I would prefer that your finding is credited to you based on the pull request.

**Pull request closed without merging**
