### PR TITLE
Users can choose client type installation: Runtime, Administrator, ..., using two new attribute

### PR DESCRIPTION
**Pull request by giomori**
modified:   attributes/default.rb
	modified:   metadata.json
	modified:   metadata.rb
	modified:   recipes/clibin.rb
	modified:   templates/default/cli11R23.rsp.erb

### CODE REVIEW

**Comment by aririikonen** [comment]
gilmori,

Thank you for the pull request. A very nice idea! I don't have time to test the code, but I'm sure you've done some smoke tests.

**Comment by aririikonen** [comment]
Oh, almost forgot. We would need to update the README.md with the new attributes. Could you?

**Comment by giomori** [comment]
Uh, I forgot documentation ...
very unusual, isn't it ???!!!

I'll do it, sorry,
Giovanni


2016-07-22 13:52 GMT+02:00 Ari Riikonen <notifications@github.com>:

**Comment by aririikonen** [comment]
Thanks giomori!

**Pull request merged**
